name: BorderPlugin
main: com.mc1510ty.TPBorder.TPBorder
version: 1.1.1
api-version: 1.21

commands:
  setborder:
    description: ワールドボーダーの半径を設定します
    usage: /setborder <半径>
    permission: borderplugin.set
    aliases: []
permissions:
  borderplugin.set:
    description: ボーダーを設定できる権限
    default: op
